config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to:'pages#home'
  
  #get '/paws', to: 'paw#index'
  #get '/paws/new', to: 'paws#new', as: 'new_paw'
  #post '/paws', to: 'paws#create'
  #get '/paws/:id/edit', to: 'paws#edit', as: 'edit_paw'
  #patch '/paws/:id', to: 'paws#update'
  #get 'paws/:id', to: 'paws#show', as: 'paw'
  #delete '/paws/:id', to: 'paws#destroy'
  
  resources :paws
end

app/models/pal.rb
class Pal < ActiveRecord::Base
 has_many :paws
 has_many :likes
 before_save { self.email = email.downcase }
 validates :palname, presence: true,length: { minimum: 3,maximum: 40 }
 
 VALID_EMAIL_REGEX =  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

 validates :email, presence: true,length: {maximum: 105 },
                                      uniqueness: { case_sensitive: false },
                                      format: { with: VALID_EMAIL_REGEX }

end 
 

app/models/paw.rb
class Paw < ActiveRecord::Base
belongs_to :pal
has_many :likes
 validates :pal_id, presence: true
 validates :name, presence: true, length: { minimum: 5, maximum: 100 }
 validates :summary, presence: true, length: {minimum: 10, maximum: 150 }
 validates :description, presence: true, length: { minimum: 20, maximum: 500 }
 mount_uploader :picture, PictureUploader
 validate :picture_size

 private
  def picture_size
   if picture.size > 5.megabyte
    errors.add(:picture, "should be less than 5MB")
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/paws_controller.rb
class PawsController < ApplicationController
  
  def index
    @paws = Paw.all
  end
  def show
    @paw = Paw.find(params[:id])
  end
  
  def new
    @paw =Paw.new
    
  end
  
  def create
    @paw = Paw.new(paw_params)
    @paw.pal = Pal.find(4)
    if @paw.save
      flash[:success] = "your Paw was created succesfully!"
      redirect_to paws_path
      
    else 
      render :new
    end
  end
  
  def edit
    @paw = Paw.find(params[:id])
    
  end
  
  def update
    @paw = Paw.find(params[:id])
    if @paw.update(paw_params)
      #do something
      flash[:success] = "your pawpage was updated succesfully!"
      redirect_to paw_path(@paw)
    else
      render :edit
    end
  end
  
  private
  
    def paw_params
      params.require(:paw).permit(:name, :summary, :description, :picture)
    end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper

def gravatar_for(pal, option = { size: 80 })
  gravatar_id = Digest::MD5::hexdigest(pal.email.downcase)
  size = option[:size]
  gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: pal.palname, class: "gravatar") 
end
end

app/views/layouts/_footer.html.erb
<div class= "footer">
  
  <p>&copy; PawFriends by smrithi fredric2016</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %>
      <a class="close" data-dismiss="alert">&#215;</a>
      
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "pawFriends", root_path, class:"btn btn-lg btn-success",id:"logo"%>
  <div class="nav-item">
    <%= link_to "link1", "",class: "btn btn-default btn-warning"%>
  </div>
  <div class="nav-item">
    <%= link_to "link1", "",class: "btn btn-default btn-warning"%>
  </div>
  <div class="nav-item">
    <%= link_to "New Paw", new_paw_path,class: "btn btn-default btn-warning"%>
  </div>
  
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PawFriends</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<div class= "container">
  <%= render 'layouts/messages' %>

<%= yield %>
<%= render 'layouts/footer'%>
</div>
</body>
</html>

app/views/pages/home.html.erb
<div class= "center jumbotron">
  <h1>Welcome to PawFriends</h1>
  <h2>
    This is the home page for the animal lovers all over the world.
    I have dedicated this web to animals.
  </h2>
  
  <%= link_to "Sign up now!", "",class: "btn btn-lg btn-success" %>
</div>
<div class= "row">
  <div class= "col-lg-4">
    
    <h3 class= "midrow">
      Meet paws as Guest Users
    </h3>
    <h2 class= "left">Browse and view paws as a Guest and Sign up later</h2>
    <p><%= link_to "Browse PawFriends",paws_path,class: "btn btn-warning btn-small"%></p>
  </div>
  
  <div class= "col-lg-4">
    
    <h3 class= "midrow">
      Meet paws as Guest Users
    </h3>
    <h2 class= "left">Browse and view paws as a Guest and Sign up later</h2>
    <p><%= link_to "Browse PawFriends","",class: "btn btn-warning btn-small"%></p>
  </div>
  
  <div class= "col-lg-4">
    
    <h3 class= "midrow">
      Meet paws as Guest Users
    </h3>
    <h2 class= "left">Browse and view paws as a Guest and Sign up later</h2>
    <p><%= link_to "Browse PawFriends","",class: "btn btn-warning btn-small"%></p>
  </div>
</div>

app/views/paws/_form.html.erb
<%= render 'shared/errors', obj: @paw %>

<div class="row">
<div class= "well col-md-8 col-md-offset-2">
  <%= form_for(@paw, html: { multipart: true }) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :summary %>
  <%= f.text_field :summary %>
  <%= f.label :description %>
  <%= f.text_area :description, rows: 10 %>
  
  
  
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  
  <%= f.submit(@paw.new_record? ? 'Create Paw' : 'Edit Pawpawpage', class: "btn btn-success") %>
  <% end %>
</div>
</div>

<script type="text/javascript">
  
  $('#paw_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert('Maximum file size is 5MB. Please choose a smaller file');
    }
  });
</script>

app/views/paws/edit.html.erb
 <%= render 'shared/page_title', title: "Edit Paw page" %>
<%= render 'form' %>

app/views/paws/index.html.erb
<%= render 'shared/page_title', title: "My Pets" %>
 
 <% @paws.each do |paw| %>
 <div class="row">
   <div class="col-md-2">
     <section class="pal_info center">
       <%= gravatar_for paw.pal, size:100 %>
       <h5>Pal Name: <%= paw.pal.palname %></h5>
     </section>
   </div>
   <div class="col-lg-6 well">
     <h4><%=link_to paw.name, paw_path(paw) %></h4>
<p><%= paw.summary %></p>
<p>
<span class='quit'><small><%= time_ago_in_words(paw.created_at) %></small></span>
  </p> 
   </div>
   
   <div class="col-md-4">
    <%= image_tag(paw.picture.url, size: "250x150", class: "gravatar") if paw.picture? %>
   </div>
   
   
 </div>
 <hr/>
 <% end %>

app/views/paws/new.html.erb
 <%= render 'shared/page_title', title: "Create new Paw page" %>

<%= render 'form' %>

app/views/paws/show.html.erb
<%= render 'shared/page_title', title: @paw.name %>
<div class="row">
  <div class="col-md-4 pull-right center">
    <%= gravatar_for @paw.pal, size: 200 %>
    <p>
      <h5>
        Brought to you by: <%= @paw.pal.palname %>
      </h5>
    </p>
  </div>
  <div class="col-md-8 ">
    <%= link_to "Edit this pawpage", edit_paw_path(@paw), class: "btn btn-success pull-right" %>
    
    <h3><%= @paw.summary %></h3>
    
    <div class="show_paw">
      
      <%= image_tag(@paw.picture.url, class: "gravatar") if @paw.picture? %>
    </div>
    
    <div class="well">
      <p>
        <strong>Description:</strong>
      </p>
      <%= simple_format(@paw.description) %>
      <div class="pull-right">
        <%= link_to" " do %>
         <i class="glyphicon glyphicon-thumbs-up"></li></i>
        <% end %> &nbsp &nbsp &nbsp &nbsp
        <div class="pull-right">
        <%= link_to" " do %>
         <i class="glyphicon glyphicon-thumbs-down"></li></i>
        <% end %> 
      </div>
      
    </div>
  </div>
</div>

<h5><%= link_to 'Return to Paws Listing', paws_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="alert alert-danger col-md-8 col-md-offset-2">
  <h5> Please correct the following errors:</h5>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li> <%= msg %></li>
    <% end %>
  </ul>

  
  </div>
</div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %>   </h1>
  <hr/> 
</p>